name: Bootc TOML Action
description: Generate a config.toml file for Bootc.
author: Rory Schellekens

inputs:
  name:
    description: 'The name of the user.'
    required: true
  password:
    description: 'The password of the user.'
    required: true
  key:
    description: 'The public SSH key for the user.'
    required: true
#  groups:
#    description: 'Currently hardcoded to wheel group'

outputs:
  output-filename:
    description: 'Returning config.toml for the moment.'

runs:
  using: node20
  main: dist/index.js
